name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install --silent
      - run: npm run build
      # - run: npm run test
      # - run: echo ${{ secrets.SECRET_EXAMPLE }}
      - run: npm run deploy -- --token=random_token_test
